In [90]:
import numpy as np
import math as m

In [91]:
#prob 1
x=2
y=-4
a=[[x,y]]
p= m.pi/6
q=m.cos(p)
r=m.sin(p)
b=[[q,-r],[r,q]]
matrix=np.dot(a,b)
print(matrix)


[[-0.26794919 -4.46410162]]


In [92]:
#prob 2
x=2
y=-4
a=[[x,y]]
p= m.pi/6
q=m.cos(p)
r=m.sin(p)

b=[[q,r],[-r,q]]

matrix=np.dot(a,b)
print(matrix)


[[ 3.73205081 -2.46410162]]


In [93]:
#prob 3
x=2
y=-4
a=[[x,y]]
sx=0
yx=1
b=[[sx,0],[0,yx]]

matrix=np.dot(a,b)
print(matrix)


[[ 0 -4]]


In [94]:
#prob 4
x=2
y=-4
a=[[x,y]]
sx=1
yx=0
b=[[sx,0],[0,yx]]

matrix=np.dot(a,b)
print(matrix)


[[2 0]]


In [95]:
#prob 5
x=2
y=-4
a=[[x,y]]
sx=0
yx=0
b=[[sx,0],[0,yx]]

matrix=np.dot(a,b)
print(matrix)


[[0 0]]


In [96]:
#prob 6
x=2
y=-4
a=[[x,y]]
sx=1
yx=1
b=[[sx,0],[0,yx]]

matrix=np.dot(a,b)
print(matrix)


[[ 2 -4]]


In [97]:
#prob 7
x=2
y=-4
a=[[x, y]]
tx=0
ty=1
b=[[tx,ty]]

matrix=np.add(a,b)
print(matrix)


[[ 2 -3]]


In [98]:
#prob 8
x=2
y=-4
a=[[x, y]]
tx=1
ty=0
b=[[tx,ty]]

matrix=np.add(a,b)
print(matrix)



[[ 3 -4]]


In [99]:
#prob 9
x=2
y=-4
a=[[x, y]]
tx=1
ty=1
b=[[tx,ty]]

matrix=np.add(a,b)
print(matrix)


[[ 3 -3]]


In [100]:
#prob 10
x=2
y=-4
a=[[x, y]]
tx=0
ty=0
b=[[tx,ty]]

matrix=np.add(a,b)
print(matrix)


[[ 2 -4]]
